FROM ubuntu:latest

# Update APT package index
RUN apt-get update

# Upgrade installed packages
RUN apt-get upgrade -y

# Set a command to be executed when the container starts
CMD echo "Hello, World!"
