version: '3'
services:
  back-end:
    build: # Build the image
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task4 # Name of the image

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task4

    depends_on: # Wait for the back-end to start
      - back-end
  proxy:
      build:
        context: ./proxy
        dockerfile: Dockerfile
      image: softy-pinko-proxy:task5
      ports:
        - "80:80"
      depends_on:
        - back-end
        - front-end
